"""XML-driven HQ bảng kê generator (approach A).

Reads `config/bang-ke-config.xml` and produces an xlsx workbook from
scratch — no form-mau xlsx template is consulted. The XML owns all
visual/layout decisions; this module just turns it into openpyxl calls.

Output style is intentionally consistent across all 5 criteria
(LVC/RVC/CTH/CTSH/PSR): same font, page, borders, column widths.
Per-criterion variations are the title, Phụ lục number, whether to
show the LVC cost-buildup block, and the conclusion sentence.

If you want to change look & feel, edit the XML — do not edit this file.
"""
from __future__ import annotations

from dataclasses import dataclass, field as dataclass_field
from decimal import Decimal, InvalidOperation
from functools import lru_cache
from io import BytesIO
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config" / "bang-ke-config.xml"

# Inches per cm for openpyxl page margin conversion.
_CM_PER_INCH = 2.54


# ---- dataclass mirror of the XML structure -------------------------------


@dataclass
class StyleSpec:
    font_name: str = "Times New Roman"
    font_size: int = 11
    font_color: str = "000000"
    title_size: int = 14
    title_bold: bool = True
    subtitle_size: int = 10
    subtitle_italic: bool = True
    phu_luc_size: int = 11
    phu_luc_italic: bool = True
    table_header_size: int = 10
    table_header_bold: bool = True
    table_body_size: int = 10
    conclusion_size: int = 11
    conclusion_bold: bool = True
    notes_size: int = 9
    notes_italic: bool = True
    signature_size: int = 10
    table_header_fill: str = "E7E6E6"
    summary_fill: str = "F2F2F2"
    border_style: str = "thin"
    border_color: str = "000000"
    number_decimals: int = 2
    number_thousand_sep: bool = True
    date_pattern: str = "dd/mm/yyyy"
    page_paper: str = "A4"
    orientation: str = "landscape"
    margin_top_cm: float = 2.0
    margin_bottom_cm: float = 1.5
    margin_left_cm: float = 2.0
    margin_right_cm: float = 1.5
    fit_width_pages: int = 1


@dataclass
class ColumnSpec:
    key: str
    header: str
    width: float
    align: str
    only_on: str | None = None
    skip_on: str | None = None


@dataclass
class FieldSpec:
    label: str
    field: str
    format: str | None = None


@dataclass
class SignatureSpec:
    date_line: str
    lines: list[tuple[str, bool]] = dataclass_field(default_factory=list)


@dataclass
class CostBuildupSection:
    roman: str
    label: str
    input: str | None = None
    formula: str | None = None
    auto_from: str | None = None


@dataclass
class FormSpec:
    criterion: str
    phu_luc: str
    title: str
    legal_note: str
    conclusion: str
    show_cost_buildup: bool


@dataclass
class BangKeConfig:
    style: StyleSpec
    columns: list[ColumnSpec]
    header_left: list[FieldSpec]
    header_right: list[FieldSpec]
    cost_buildup: list[CostBuildupSection]
    signature: SignatureSpec
    notes: list[str]
    forms: dict[str, FormSpec]


# ---- public API ----------------------------------------------------------


@lru_cache(maxsize=1)
def load_config() -> BangKeConfig:
    return _parse(CONFIG_PATH)


def clear_config_cache() -> None:
    load_config.cache_clear()


def render_form(criterion: str, case: dict, product: dict) -> bytes:
    """Render a single bảng kê sheet for a case/product into xlsx bytes."""
    cfg = load_config()
    form = cfg.forms.get(criterion.upper())
    if form is None:
        raise ValueError(f"No <form criterion={criterion!r}> in {CONFIG_PATH.name}")
    wb = Workbook()
    wb.remove(wb.active)
    ws = wb.create_sheet(_sheet_title(product, criterion))
    _apply_page_setup(ws, cfg.style)
    _render_sheet(ws, cfg, form, case, product)
    out = BytesIO()
    wb.save(out)
    return out.getvalue()


def render_case(case: dict, criterion_for_product) -> bytes:
    """Render the full HQ bảng kê workbook for a case (one sheet per product).

    `criterion_for_product` is a callable that returns the criterion code
    for a given product dict (LVC/RVC/CTH/CTSH/PSR).
    """
    cfg = load_config()
    wb = Workbook()
    wb.remove(wb.active)
    for product in case.get("products") or []:
        criterion = (criterion_for_product(product) or "").upper()
        form = cfg.forms.get(criterion)
        if form is None:
            continue
        ws = wb.create_sheet(_sheet_title(product, criterion))
        _apply_page_setup(ws, cfg.style)
        _render_sheet(ws, cfg, form, case, product)
    if not wb.sheetnames:
        ws = wb.create_sheet("README")
        ws["A1"] = "Hồ sơ chưa có TP nào sẵn sàng để xuất bảng kê HQ."
    out = BytesIO()
    wb.save(out)
    return out.getvalue()


# ---- XML parsing ----------------------------------------------------------


def _parse(path: Path) -> BangKeConfig:
    tree = ET.parse(path)
    root = tree.getroot()
    style = _parse_style(root.find("style"))
    columns = [
        ColumnSpec(
            key=el.get("key", ""),
            header=el.get("header", ""),
            width=float(el.get("width", "10")),
            align=el.get("align", "left"),
            only_on=el.get("only-on"),
            skip_on=el.get("skip-on"),
        )
        for el in (root.find("columns") or []).findall("column")
    ]
    header = root.find("header")
    header_left = _parse_fields(header.find("left-column"))
    header_right = _parse_fields(header.find("right-column"))
    cost_buildup = [
        CostBuildupSection(
            roman=el.get("roman", ""),
            label=el.get("label", ""),
            input=el.get("input"),
            formula=el.get("formula"),
            auto_from=el.get("auto-from"),
        )
        for el in (root.find("cost-buildup") or []).findall("section")
    ]
    sig_el = root.find("signature")
    signature = SignatureSpec(
        date_line=(sig_el.findtext("date-line") or "").strip(),
        lines=[
            ((line.text or "").strip(), line.get("italic", "false").lower() == "true")
            for line in sig_el.findall("line")
        ],
    )
    notes = [(el.text or "").strip() for el in (root.find("notes") or []).findall("note")]
    forms: dict[str, FormSpec] = {}
    for el in (root.find("forms") or []).findall("form"):
        criterion = el.get("criterion", "").upper()
        forms[criterion] = FormSpec(
            criterion=criterion,
            phu_luc=el.get("phu-luc", ""),
            title=(el.findtext("title") or "").strip(),
            legal_note=(el.findtext("legal-note") or "").strip(),
            conclusion=(el.findtext("conclusion") or "").strip(),
            show_cost_buildup=el.get("show-cost-buildup", "false").lower() == "true",
        )
    return BangKeConfig(
        style=style,
        columns=columns,
        header_left=header_left,
        header_right=header_right,
        cost_buildup=cost_buildup,
        signature=signature,
        notes=notes,
        forms=forms,
    )


def _parse_style(el: ET.Element | None) -> StyleSpec:
    spec = StyleSpec()
    if el is None:
        return spec
    page = el.find("page")
    if page is not None:
        spec.page_paper = page.get("paper", spec.page_paper)
        spec.orientation = page.get("orientation", spec.orientation)
        spec.margin_top_cm = float(page.get("margin-top", spec.margin_top_cm))
        spec.margin_bottom_cm = float(page.get("margin-bottom", spec.margin_bottom_cm))
        spec.margin_left_cm = float(page.get("margin-left", spec.margin_left_cm))
        spec.margin_right_cm = float(page.get("margin-right", spec.margin_right_cm))
        spec.fit_width_pages = int(page.get("fit-width-pages", spec.fit_width_pages))
    base_font = el.find("font")
    if base_font is not None:
        spec.font_name = base_font.get("name", spec.font_name)
        spec.font_size = int(base_font.get("size", spec.font_size))
        spec.font_color = base_font.get("color", spec.font_color)

    def _font(tag: str, size_attr: str, *bool_attrs: str) -> None:
        ent = el.find(tag)
        if ent is None:
            return
        for attr in bool_attrs:
            val = ent.get(attr, "").lower()
            if val:
                setattr(spec, f"{tag.replace('-font', '').replace('-', '_')}_{attr}", val == "true")
        if ent.get("size"):
            setattr(spec, f"{tag.replace('-font', '').replace('-', '_')}_size", int(ent.get("size")))

    _font("title-font", "size", "bold")
    _font("subtitle-font", "size", "italic")
    _font("phu-luc-font", "size", "italic")
    _font("table-header-font", "size", "bold")
    _font("table-body-font", "size")
    _font("conclusion-font", "size", "bold")
    _font("notes-font", "size", "italic")
    _font("signature-font", "size")
    for fill in el.findall("fill"):
        region = fill.get("region")
        color = fill.get("color", "")
        if region == "table-header":
            spec.table_header_fill = color
        elif region == "summary-block":
            spec.summary_fill = color
    for border in el.findall("border"):
        region = border.get("region")
        if region == "table":
            spec.border_style = border.get("style", spec.border_style)
            spec.border_color = border.get("color", spec.border_color)
    nf = el.find("number-format")
    if nf is not None:
        spec.number_decimals = int(nf.get("decimals", spec.number_decimals))
        spec.number_thousand_sep = nf.get("thousand-sep", "true").lower() == "true"
    df = el.find("date-format")
    if df is not None:
        spec.date_pattern = df.get("pattern", spec.date_pattern)
    return spec


def _parse_fields(el: ET.Element | None) -> list[FieldSpec]:
    if el is None:
        return []
    return [
        FieldSpec(
            label=node.get("label", ""),
            field=node.get("field", ""),
            format=node.get("format"),
        )
        for node in el.findall("field")
    ]


# ---- rendering -----------------------------------------------------------


def _render_sheet(ws, cfg: BangKeConfig, form: FormSpec, case: dict, product: dict) -> None:
    style = cfg.style
    columns = [c for c in cfg.columns if _column_visible(c, form.criterion)]
    n_cols = len(columns)
    last_col_letter = get_column_letter(n_cols)

    row = 1
    # Phụ lục (right-aligned single cell across the table)
    ws.cell(row=row, column=n_cols, value=form.phu_luc).font = _font(style, italic=True, size=style.phu_luc_size)
    ws.cell(row=row, column=n_cols).alignment = Alignment(horizontal="right")
    row += 1

    # Title
    _merge_and_set(
        ws, row, 1, row, n_cols,
        text=form.title, font=_font(style, bold=True, size=style.title_size),
        align=Alignment(horizontal="center", vertical="center", wrap_text=True),
    )
    ws.row_dimensions[row].height = 22
    row += 1

    # Legal note (sub-title)
    _merge_and_set(
        ws, row, 1, row, n_cols,
        text=form.legal_note,
        font=_font(style, italic=True, size=style.subtitle_size),
        align=Alignment(horizontal="center", vertical="center"),
    )
    row += 2  # blank spacer

    # Header (two-column key/value grid)
    fields = _build_field_table(case, product, form)
    left = list(cfg.header_left)
    right = list(cfg.header_right)
    rows_needed = max(len(left), len(right))
    half = max(1, n_cols // 2)
    for i in range(rows_needed):
        if i < len(left):
            _write_header_field(ws, row, 1, half, left[i], fields, style)
        if i < len(right):
            _write_header_field(ws, row, half + 1, n_cols, right[i], fields, style)
        row += 1
    row += 1  # spacer

    # Table header
    table_header_row = row
    header_font = _font(style, bold=True, size=style.table_header_size)
    header_fill = PatternFill(start_color=style.table_header_fill, end_color=style.table_header_fill, fill_type="solid")
    border_side = Side(style=style.border_style, color=style.border_color)
    cell_border = Border(left=border_side, right=border_side, top=border_side, bottom=border_side)
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for col_index, col_spec in enumerate(columns, start=1):
        cell = ws.cell(row=row, column=col_index, value=col_spec.header)
        cell.font = header_font
        cell.fill = header_fill
        cell.border = cell_border
        cell.alignment = header_align
        ws.column_dimensions[get_column_letter(col_index)].width = col_spec.width
    ws.row_dimensions[row].height = 32
    row += 1

    # Body rows
    body_font = _font(style, size=style.table_body_size)
    sum_origin = Decimal("0")
    sum_non_origin = Decimal("0")
    materials = product.get("materials") or []
    overrides = product.get("origin_sheet_material_overrides") or {}
    counter = 1
    for index, material in enumerate(materials):
        override = overrides.get(str(index)) if isinstance(overrides.get(str(index)), dict) else {}
        if override.get("deleted"):
            continue
        values, origin_value, non_origin_value = _build_material_row(material, override, product, counter)
        sum_origin += origin_value
        sum_non_origin += non_origin_value
        _write_body_row(ws, row, columns, values, body_font, cell_border, style)
        row += 1
        counter += 1
    for key, value in overrides.items():
        if not key.startswith("added_") or not isinstance(value, dict):
            continue
        values, _, _ = _build_added_row(value, product, counter)
        _write_body_row(ws, row, columns, values, body_font, cell_border, style)
        row += 1
        counter += 1

    # Totals row (always shown below the body so HQ can verify origin/non-origin sums)
    total_row = row
    _write_totals_row(
        ws,
        row=total_row,
        columns=columns,
        sum_origin=sum_origin,
        sum_non_origin=sum_non_origin,
        font=_font(style, bold=True, size=style.table_body_size),
        border=cell_border,
        style=style,
    )
    row += 2

    # LVC cost-buildup block (LVC + RVC)
    fob = _decimal(product.get("fob") or "0")
    if form.show_cost_buildup:
        cost_buildup_inputs = _coerce_cost_buildup(product.get("cost_buildup"))
        row = _write_cost_buildup(
            ws, row, cfg, n_cols, fob, sum_origin, sum_non_origin, style, cell_border,
            cost_buildup_inputs=cost_buildup_inputs,
        )
        row += 1

    # Conclusion
    ratio_percent = _ratio_percent(fob, sum_non_origin)
    conclusion_text = form.conclusion.format(ratio_percent=ratio_percent, criterion=form.criterion)
    _merge_and_set(
        ws, row, 1, row, n_cols,
        text=conclusion_text,
        font=_font(style, bold=True, size=style.conclusion_size),
        align=Alignment(horizontal="left", vertical="center"),
        top_border=border_side,
    )
    row += 2

    # Signature block (right-aligned column on the right half)
    sig_col_start = max(1, n_cols - 4)
    for line in [cfg.signature.date_line] + [text for text, _ in cfg.signature.lines]:
        ws.cell(row=row, column=sig_col_start, value=line).font = _font(style, size=style.signature_size)
        ws.merge_cells(start_row=row, start_column=sig_col_start, end_row=row, end_column=n_cols)
        ws.cell(row=row, column=sig_col_start).alignment = Alignment(horizontal="center")
        row += 1
    # Re-apply italic on the last "(Ký tên, đóng dấu)" line
    if cfg.signature.lines and cfg.signature.lines[-1][1]:
        ws.cell(row=row - 1, column=sig_col_start).font = _font(style, italic=True, size=style.signature_size)
    row += 1

    # Notes
    notes_font = _font(style, italic=True, size=style.notes_size)
    ws.cell(row=row, column=1, value="Ghi chú:").font = _font(style, bold=True, size=style.notes_size)
    row += 1
    for note in cfg.notes:
        _merge_and_set(
            ws, row, 1, row, n_cols,
            text=f"- {note}",
            font=notes_font,
            align=Alignment(horizontal="left", vertical="top", wrap_text=True),
        )
        ws.row_dimensions[row].height = 28
        row += 1

    # Print area covers the full sheet.
    ws.print_area = f"A1:{last_col_letter}{row - 1}"


# ---- helpers --------------------------------------------------------------


def _column_visible(col: ColumnSpec, criterion: str) -> bool:
    if col.only_on and col.only_on.upper() != criterion:
        return False
    if col.skip_on and col.skip_on.upper() == criterion:
        return False
    return True


def _build_material_row(
    material: dict,
    override: dict,
    product: dict,
    counter: int,
) -> tuple[dict, Decimal, Decimal]:
    material_code = override.get("material_code") or material.get("material_code", "")
    material_name = override.get("name") or material.get("material_description", "")
    norm = override.get("norm_per_unit") or material.get("bom_qty_per", "0")
    consumed_qty = _decimal(material.get("consumed_qty") or norm)
    use_vnd = (product.get("origin_sheet_currency_mode") or "native").strip().lower() == "vnd"
    unit_price = _decimal(_pick_currency_value(material, "unit_value", use_vnd, product))
    material_value = _decimal(_pick_currency_value(material, "material_value", use_vnd, product))
    is_origin = str(material.get("origin_status") or "non_origin") == "origin"
    origin_value = material_value if is_origin else Decimal("0")
    non_origin_value = material_value if not is_origin else Decimal("0")
    values = {
        "stt": counter,
        "name": material_name,
        "material_code": material_code,
        "hs": material.get("hs_code", ""),
        "uom": material.get("uom", ""),
        "norm": _decimal(norm),
        "qty": consumed_qty,
        "unit_price": unit_price,
        "origin_value": origin_value,
        "non_origin_value": non_origin_value,
        "country": material.get("origin_country", ""),
        "import_decl_no": material.get("import_declaration_no", ""),
        "import_decl_date": (
            material.get("import_declaration_date")
            or material.get("declaration_date")
            or material.get("registration_date")
            or ""
        ),
        "co_doc_no": material.get("source_document_ref", ""),
        "co_doc_date": material.get("source_document_date", ""),
    }
    return values, origin_value, non_origin_value


def _resolve_target_currency_for_product(product: dict) -> str:
    from app.bang_ke_renderer import _resolve_target_currency
    use_vnd = (product.get("origin_sheet_currency_mode") or "native").strip().lower() == "vnd"
    return _resolve_target_currency(product, use_vnd)


def _pick_currency_value(material: dict, base_key: str, use_vnd: bool, product: dict | None = None) -> str:
    """Mirror of bang_ke_renderer._pick_currency_value with bidirectional
    conversion (VND ↔ nguyên tệ). See that function's docstring for the
    direction matrix."""
    from app.bang_ke_renderer import _pick_currency_value as renderer_pick
    return renderer_pick(material, base_key, use_vnd, product)


def _build_added_row(value: dict, product: dict, counter: int) -> tuple[dict, Decimal, Decimal]:
    values = {
        "stt": counter,
        "name": value.get("name", ""),
        "material_code": value.get("material_code", ""),
        "hs": value.get("hs_code", ""),
        "uom": value.get("uom", ""),
        "norm": _decimal(value.get("norm_per_unit", "0")),
    }
    return values, Decimal("0"), Decimal("0")


def _write_body_row(ws, row: int, columns: list[ColumnSpec], values: dict, font: Font, border: Border, style: StyleSpec) -> None:
    for col_index, col in enumerate(columns, start=1):
        cell = ws.cell(row=row, column=col_index, value=values.get(col.key, ""))
        cell.font = font
        cell.border = border
        cell.alignment = Alignment(horizontal=col.align, vertical="top", wrap_text=True)
        if isinstance(values.get(col.key), Decimal):
            cell.number_format = _numeric_format(style)


def _write_totals_row(ws, row: int, columns: list[ColumnSpec], sum_origin: Decimal, sum_non_origin: Decimal, font: Font, border: Border, style: StyleSpec) -> None:
    label_col = 1
    for col_index, col in enumerate(columns, start=1):
        cell = ws.cell(row=row, column=col_index)
        cell.font = font
        cell.border = border
        cell.fill = PatternFill(start_color=style.summary_fill, end_color=style.summary_fill, fill_type="solid")
        if col.key == "origin_value":
            cell.value = sum_origin
            cell.number_format = _numeric_format(style)
            cell.alignment = Alignment(horizontal="right")
        elif col.key == "non_origin_value":
            cell.value = sum_non_origin
            cell.number_format = _numeric_format(style)
            cell.alignment = Alignment(horizontal="right")
        elif col_index == label_col:
            cell.value = "TỔNG"
            cell.alignment = Alignment(horizontal="center")
        else:
            cell.alignment = Alignment(horizontal=col.align)


def _write_cost_buildup(
    ws,
    start_row: int,
    cfg: BangKeConfig,
    n_cols: int,
    fob: Decimal,
    sum_origin: Decimal,
    sum_non_origin: Decimal,
    style: StyleSpec,
    border: Border,
    cost_buildup_inputs: dict[str, Decimal] | None = None,
) -> int:
    label_font = _font(style, bold=True, size=style.table_body_size)
    value_font = _font(style, size=style.table_body_size)
    fill = PatternFill(start_color=style.summary_fill, end_color=style.summary_fill, fill_type="solid")
    row = start_row
    inputs = cost_buildup_inputs or {}
    # Label/value sections occupy 2 cells: left half = label, right cell = numeric.
    label_end_col = max(1, n_cols - 1)
    value_col = n_cols
    section_totals: dict[str, Decimal] = {}
    for section in cfg.cost_buildup:
        label = f"{section.roman}. {section.label}"
        for col in range(1, n_cols + 1):
            cell = ws.cell(row=row, column=col)
            cell.border = border
            cell.fill = fill
        ws.cell(row=row, column=1, value=label).font = label_font
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=label_end_col)
        ws.cell(row=row, column=1).alignment = Alignment(horizontal="left", vertical="center")
        ws.cell(row=row, column=value_col).font = value_font
        ws.cell(row=row, column=value_col).alignment = Alignment(horizontal="right", vertical="center")
        ws.cell(row=row, column=value_col).number_format = _numeric_format(style)
        if section.auto_from == "material-totals":
            value = sum_origin + sum_non_origin
        elif section.formula == "I+II+III":
            value = section_totals.get("I", Decimal(0)) + section_totals.get("II", Decimal(0)) + section_totals.get("III", Decimal(0))
        elif section.formula == "IV+V":
            value = section_totals.get("IV", Decimal(0)) + section_totals.get("V", Decimal(0))
        elif section.formula == "fob":
            value = fob
        elif section.input:
            value = inputs.get(section.input, Decimal(0))
        else:
            value = Decimal(0)
        section_totals[section.roman] = value
        ws.cell(row=row, column=value_col, value=value if value else None)
        row += 1
    return row


def _build_field_table(case: dict, product: dict, form: FormSpec) -> dict[str, Any]:
    quantity = product.get("quantity", "") or "0"
    currency_mode = (product.get("origin_sheet_currency_mode") or "native").strip().lower()
    fob_raw = product.get("fob", "") or "0"
    if currency_mode == "vnd" and product.get("fob_vnd"):
        fob_raw = product["fob_vnd"]
    fob_pretty = _format_number(_decimal(fob_raw), decimals=2, thousand_sep=True)
    declaration_no = product.get("source_declaration_no") or _first_non_empty(
        (case.get("shipment") or {}).get("export_declaration_nos") or []
    )
    declaration_date = (
        product.get("source_declaration_date")
        or product.get("export_declaration_date")
        or ""
    )
    criterion_text = (
        product.get("origin_sheet_effective_criteria_text")
        or product.get("documented_result")
        or form.criterion
    )
    uom = product.get("uom") or product.get("unit") or product.get("export_unit", "")
    return {
        "merchant": (
            case.get("customer_legal_name")
            or case.get("customer", "")
            or case.get("client_name", "")
            or case.get("client_id", "")
        ),
        "tax_code": case.get("customer_tax_code", "") or case.get("client_tax_code", ""),
        "criterion_text": criterion_text,
        "product_name": product.get("name", ""),
        "finished_hs": product.get("finished_hs", ""),
        "quantity": quantity,
        "uom": uom,
        "fob": fob_raw,
        "declaration": {"no": declaration_no, "date": declaration_date} if declaration_no else None,
        "quantity_uom": {"quantity": quantity, "uom": uom},
        "fob_with_currency": {
            "fob": fob_pretty,
            "currency": _resolve_target_currency_for_product(product),
        },
    }


def _write_header_field(ws, row: int, start_col: int, end_col: int, field: FieldSpec, fields: dict, style: StyleSpec) -> None:
    raw = fields.get(field.field)
    if field.format and isinstance(raw, dict):
        try:
            value = field.format.format(**raw)
        except KeyError:
            value = ""
    elif raw is None:
        value = ""
    else:
        value = str(raw)
    # Label spans the first 2 cells of the field block; value spans the rest.
    # The table column widths (STT=5, etc.) leave a single label cell far too
    # narrow for any real label — merging two cells gives Vietnamese labels
    # of 15-25 chars enough room without overflowing into the value.
    label_end = min(start_col + 1, end_col)
    label_cell = ws.cell(row=row, column=start_col, value=field.label)
    label_cell.font = _font(style, bold=True, size=style.font_size)
    label_cell.alignment = Alignment(horizontal="left", vertical="center")
    if label_end > start_col:
        ws.merge_cells(start_row=row, start_column=start_col, end_row=row, end_column=label_end)
    value_start = label_end + 1
    if value_start > end_col:
        value_start = end_col
    value_cell = ws.cell(row=row, column=value_start, value=value)
    value_cell.font = _font(style, size=style.font_size)
    value_cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
    if end_col > value_start:
        ws.merge_cells(start_row=row, start_column=value_start, end_row=row, end_column=end_col)


def _merge_and_set(
    ws, start_row: int, start_col: int, end_row: int, end_col: int,
    *, text: str, font: Font, align: Alignment, top_border: Side | None = None,
) -> None:
    if start_row != end_row or start_col != end_col:
        ws.merge_cells(start_row=start_row, start_column=start_col, end_row=end_row, end_column=end_col)
    cell = ws.cell(row=start_row, column=start_col, value=text)
    cell.font = font
    cell.alignment = align
    if top_border is not None:
        cell.border = Border(top=top_border)


def _font(style: StyleSpec, *, size: int | None = None, bold: bool = False, italic: bool = False) -> Font:
    return Font(
        name=style.font_name,
        size=size or style.font_size,
        bold=bold,
        italic=italic,
        color=style.font_color,
    )


def _apply_page_setup(ws, style: StyleSpec) -> None:
    ws.page_setup.orientation = (
        ws.ORIENTATION_LANDSCAPE if style.orientation == "landscape" else ws.ORIENTATION_PORTRAIT
    )
    paper_codes = {"A4": 9, "Letter": 1}
    if style.page_paper in paper_codes:
        ws.page_setup.paperSize = paper_codes[style.page_paper]
    ws.page_margins.top = style.margin_top_cm / _CM_PER_INCH
    ws.page_margins.bottom = style.margin_bottom_cm / _CM_PER_INCH
    ws.page_margins.left = style.margin_left_cm / _CM_PER_INCH
    ws.page_margins.right = style.margin_right_cm / _CM_PER_INCH
    ws.page_setup.fitToWidth = style.fit_width_pages
    ws.page_setup.fitToHeight = 0
    ws.sheet_properties.pageSetUpPr.fitToPage = True
    ws.print_options.horizontalCentered = True


def _numeric_format(style: StyleSpec) -> str:
    if style.number_thousand_sep:
        return f"#,##0.{'0' * style.number_decimals}"
    return f"0.{'0' * style.number_decimals}"


def _sheet_title(product: dict, criterion: str) -> str:
    code = (product.get("code") or criterion).strip()
    safe = "".join(c for c in f"{criterion}-{code}" if c not in "[]:*?/\\")[:31]
    return safe or criterion


def _decimal(value) -> Decimal:
    if value in (None, ""):
        return Decimal("0")
    if isinstance(value, Decimal):
        return value
    try:
        return Decimal(str(value).replace(",", "").strip())
    except (InvalidOperation, ValueError):
        return Decimal("0")


def _ratio_percent(fob: Decimal, non_origin: Decimal) -> str:
    if fob <= 0:
        return "0.00"
    ratio = (fob - non_origin) / fob
    return str((ratio * Decimal("100")).quantize(Decimal("0.01")))


COST_BUILDUP_KEYS = ("labor", "overhead", "profit", "other")
"""Rollup keys the XML config references via <section input="..."> on the
bảng kê. The engine consumes these four; cost_buildup storage uses a finer
6-detail shape (wages/welfare/rent/depreciation/other_mfg/transport_storage)
plus profit — rolled up here so the engine layout (I-VIII) stays unchanged.

Rollup contract:
    labor    = wages + welfare
    overhead = rent + depreciation + other_mfg
    other    = transport_storage
    profit   = profit (direct, residual on the form)

Legacy 4-key shape (labor/overhead/profit/other) is recognised as fallback
when no detail key is present in the raw dict.
"""

_COST_BUILDUP_DETAIL_KEYS = (
    "wages", "welfare", "rent", "depreciation", "other_mfg", "transport_storage",
)


def _coerce_cost_buildup(raw) -> dict[str, Decimal]:
    if not isinstance(raw, dict):
        return {key: Decimal(0) for key in COST_BUILDUP_KEYS}
    has_details = any(str(raw.get(k) or "").strip() for k in _COST_BUILDUP_DETAIL_KEYS)
    if has_details:
        wages = _decimal(raw.get("wages"))
        welfare = _decimal(raw.get("welfare"))
        rent = _decimal(raw.get("rent"))
        depreciation = _decimal(raw.get("depreciation"))
        other_mfg = _decimal(raw.get("other_mfg"))
        transport_storage = _decimal(raw.get("transport_storage"))
        return {
            "labor": wages + welfare,
            "overhead": rent + depreciation + other_mfg,
            "profit": _decimal(raw.get("profit")),
            "other": transport_storage,
        }
    return {key: _decimal(raw.get(key)) for key in COST_BUILDUP_KEYS}


def _format_number(value: Decimal, *, decimals: int, thousand_sep: bool) -> str:
    if value == 0:
        spec = f",.{decimals}f" if thousand_sep else f".{decimals}f"
        return format(Decimal("0"), spec)
    spec = f",.{decimals}f" if thousand_sep else f".{decimals}f"
    return format(value, spec)


def _first_non_empty(values) -> str:
    for value in values or []:
        text = str(value).strip()
        if text:
            return text
    return ""
